### ISSUE TITLE
Add "Cuaderno de bitácora"

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/asrob-uc3m.github.io#16]
Migrate "Cuaderno de bitácora" from wiki to website.

**Comment by jgvictores** [comment]
Is this issue still valid?
Which one...?
http://asrob.uc3m.es/index.php?search=cuaderno+de+bitacora&title=Special%3ASearch&go=Go

**Comment by Siotma** [comment]
Actually, Printer One Cuaderno de Bitacora has been migrated [here](https://github.com/asrob-uc3m/impresoras-asrob/wiki/Printer-One-A-Clone-Wars-Story.-Cuaderno-de-Bit%C3%A1cora).
There's still some content that's only available at the old wiki, but the [old Cuaderno de Bitacora](http://asrob.uc3m.es/index.php/Printer_One:_A_Clone_Wars_Story:_Cuaderno_de_Bitacora), wont be updated anymore.

Regarding Taller de Zowimanoides Cuaderno de Bitácora, it is not migrated, but i don't think it would be highly necessary.

**Comment by David-Estevez** [comment]
Since we want to reduce the use of the wiki and favour the website, most of the "Cuadernos de Bitácora" have been migrated from the wiki. The original idea was to add them as a new page to our website, but someone (if I remember who I'll edit this post) suggested we use a GitHub repo wiki page instead, and so we did.

Right now, in G.A.M.E and Robofactory the unwritten convention is to write down the progresses of each session in the wiki page of the correspoding repo (Depending on the specific project). This makes much more easier to track the history of each project within the workgroup. The old "Cuadernos de bitácora" have been already migrated and will no longer be updated.

**Comment by jgvictores** [comment]
Yes, same happened with Robot Devastation (unwritten convention is to write down the progresses of each session in the wiki page of the correspoding repo). Ok to close this issue, or should something else be done?

**Comment by David-Estevez** [comment]
Closing as all the "Cuadernos de bitácora" have been migrated from the wiki. 

If we want to display this info in our website we will reopen this.
