### ISSUE TITLE
[Printer One] Enlace roto a grupo de Telegram

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/asrob-uc3m.github.io#19]
Enlace roto a grupo de Telegram en http://asrob-uc3m.github.io/workgroups/2017-05-28-printer-one.html

No me queda claro si es que caduca, o si ha habido un cambio a supergrupo... Con actualizarlo debería bastar.

cc: @asrob-uc3m/impresoras @Siotma

**Comment by Siotma** [comment]
Es posible que la validez de los enlaces tenga fecha de caducidad. He modificado el enlace por el actual via 322ae5b330e1596772105235119acb5ff7aea86b

Issue cerrada

**Comment by jgvictores** [comment]
Genial, gracias!
