### ISSUE TITLE
Add content (replace dummy content)

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/asrob-uc3m.github.io#2]
Add content for each active work group + ASROB:
- [ ] ASROB
- [x] MYOD
- [x] Robot Devastation
- [x] UAVs

**Comment by jgvictores** [comment]
@KFRodicio @JavierIH @RobertoHE (MYOD)
@Rodriwp (UAVs)
https://www.youtube.com/watch?v=nntGTK2Fhb0

**Comment by David-Estevez** [comment]
Cc @andrespy

**Comment by David-Estevez** [comment]
@andrespy has already updated the text for the UAVs group.

You are the only ones left, MYOD ( @KFRodicio @JavierIH @RobertoHE @Siotma )

**Comment by David-Estevez** [comment]
MYOD (@KFRodicio @JavierIH @RobertoHE @Siotma), si a día 24 de Abril no se ha recibido el texto e icono que queréis poner (o si no habéis puesto vosotros el que queráis), se ejecutará el siguiente script:

``` python
from random import choice
print "Opcion elegida:"
print choice(["Borrar apartado MYOD en web", "Dejarlo como está"])
```

Y lo que salga, salió

**Comment by JavierIH** [comment]
El proyecto ha cambiado, pero @Siotma y yo coincidimos en que el texto ahora sí se adecúa bien a lo que hacemos. Invoco a @kleiren por si acaso tiene una versión del logo con mayor calidad.

**Comment by David-Estevez** [comment]
Dejamos el texto así entonces :+1: Gracias, @JavierIH @Siotma :grin:

Si @kleiren encuentra un logo mejor y me lo pasa, me encargo de meterlo en la web.

**Comment by kleiren** [comment]
Danos acceso al repo anda @David-Estevez.
Ahí tienes una versión con más calidad.

![myodlogoaltern2](https://cloud.githubusercontent.com/assets/5618792/14708774/4daedf6c-07cd-11e6-93b0-d234c6eb4200.png)

**Comment by David-Estevez** [comment]
@kleiren os acabo de dar acceso a todos y añadir la foto de más resolución

**Comment by David-Estevez** [comment]
Made invalid by #10
