### ISSUE TITLE
Add links to playlists within groups?

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/asrob-uc3m.github.io#20]
Each working group usually has its own playlist within https://www.youtube.com/user/asrobuc3m/playlists

Maybe add links to playlists within groups, similar to `next_meeting` or `url_telegram`?

**Comment by d-marcos-m** [comment]
Hecho, quedaría tal que así. Basta con añadir una variable "url_playlist" al markdown del grupo al que queramos añadir una playlist: 

> i.e.: url_playlist: https://www.youtube.com/watch?v=CkQv48gOenw&list=PL0E72403A6C94309E

![screenshot from 2018-10-03 00-08-20](https://user-images.githubusercontent.com/14359236/46379855-78e2da00-c6a0-11e8-97f2-1e418da22611.png)

**Comment by David-Estevez** [comment]
Me dais unas alegrías cuando hacéis estas cosas! 😁😁😁

**Comment by jgvictores** [comment]
For the record, y por lo que he podido observar, implementado en:
- 6946648a415c28550f1c33e194881770d0c7e890
- 06f6e14f646328f1fd3eb4e2385f3adbdfbc4d5f

@dmarcosm Muchas gracias!!!
