### ISSUE TITLE
Quitar G+

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/asrob-uc3m.github.io#23]
Quitar G+, como resultado de https://github.com/asrob-uc3m/actas/issues/141

**Comment by JorFru** [comment]
https://plus.google.com/u/3/117320353227938266035/posts/9abMZkm2Qpn
TERMINADO
![captura de pantalla_2018-09-11_14-33-59](https://user-images.githubusercontent.com/11017088/45360416-d5863400-b5cf-11e8-98c0-c8b3566c8821.png)

**Comment by David-Estevez** [comment]
Reabro porque lo que había que hacer en esta issue no era poner la despedida (eso había que hacerlo, pero esa parte está en https://github.com/asrob-uc3m/actas/issues/141), sino eliminar el botoncito de la web que lleva a G+

![](https://media.giphy.com/media/fJhjKXCMryDEk/giphy-downsized.gif)

**Comment by jgvictores** [comment]
Done at https://github.com/asrob-uc3m/asrob-uc3m.github.io/commit/b01b4bde46f6c4bece286a57d7dda06d6685552a
