### ISSUE TITLE
Enlazar lista de correo

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/asrob-uc3m.github.io#25]
Enlazar lista de correo (está en wiki)

**Comment by d-marcos-m** [comment]
> Enlazar lista de correo (está en wiki)

https://groups.google.com/forum/#!forum/miembros-activos-asrob Esto?

**Comment by GioSunrider** [comment]
correcto

**Comment by GioSunrider** [comment]
Done.

**Comment by Siotma** [comment]
@GioSunrider Referencia el commit cuando hagas cambios en el repo: 9eb1992fe6f68b7274e231f423271f2745bcc9ac

**Comment by GioSunrider** [comment]
Vale, apuntado para la próxima! 😊 Gracias
