### ISSUE TITLE
Enlazar cuenta de Instagram

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/asrob-uc3m.github.io#27]
Contexto: https://github.com/asrob-uc3m/actas/issues/165
Tarea: añadir un enlace a Instagram en la web, junto al resto de RRSS

**Comment by GioSunrider** [comment]
He cambiado el código, en [_config.yml](https://github.com/asrob-uc3m/asrob-uc3m.github.io/blob/master/_config.yml) para añadir la cuenta de instagram y básicamente la pagina ha petado. He procedido a la eliminación de las lineas para que la pagina siguiera su curso.

El codigo añadido y eliminado era:
        
>         - id: instagram
>         name: Instagram
>         url: https://www.instagram.com/asrob_uc3m/`

**Comment by PeterBowman** [comment]
Fíjate bien en la indentación, YAML es muy puñetero a la hora de saltarse algún espacio. En el propio diff veo que hay algo que no cuadra (te sobra uno en la línea del `- id ...`). A mí me viene bien esta página para verificar: http://yaml-online-parser.appspot.com/.

**Comment by d-marcos-m** [comment]
> https://www.instagram.com/asrob_uc3m/`

editado y pusheado. Era cosa de identación y un ` que se te había colado al final del link de IG

**Comment by GioSunrider** [comment]
> > [https://www.instagram.com/asrob_uc3m/`](https://www.instagram.com/asrob_uc3m/%60)
> 
> editado y pusheado. Era cosa de identación y un ` que se te había colado al final del link de IG

No No, eso ha sido a causa de querer ponerlo bonito en el comentario.
