### ISSUE TITLE
Colocar mapa en entrada 1.0.B06

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/asrob-uc3m.github.io#31]
Añadir mapas. Dejo aquí algo que puede servir (o no) de inspiración:
- Dónde está la nave (1.0.B06) dentro del edificio 1 (Betancourt):
![photo_2018-10-31_16-03-32](https://user-images.githubusercontent.com/4448588/47801661-900bfa80-dd26-11e8-9555-6f466b08ec96.jpg)
- Dónde está ASROB dentro de la nave:
![photo_2018-10-31_16-03-25](https://user-images.githubusercontent.com/4448588/47801660-900bfa80-dd26-11e8-939b-4afa806d1334.jpg)

**Comment by jgvictores** [comment]
Vi algo de progreso en esto.

cc @L4g0 @JorFru ¿Sabéis algo?

**Comment by PeterBowman** [comment]
![20191016_150214](https://user-images.githubusercontent.com/9977198/66921756-1bf56000-f026-11e9-89c0-95a6881a00d5.jpg)

**Comment by L4g0** [comment]
Aquí el .svg creado con Inkscape por si alguien quiere mejorarlo

[CartelesASROB.zip](https://github.com/asrob-uc3m/asrob-uc3m.github.io/files/3859015/CartelesASROB.zip)

**Comment by jgvictores** [comment]
Colocada en puerta nueva versión que @JorFru subió [aquí](https://github.com/asrob-uc3m/actas/issues/97#issuecomment-562214789). Adjunto foto.

Subidos a Google Drive de ASROB:
- `Multimedia/2019/CartelesASROB/EntradaNave-conweb.pdf`
- `Multimedia/2019/CartelesASROB/editable/EntradaNave-conweb.svg`.

![photo_2020-01-09_12-08-26](https://user-images.githubusercontent.com/4448588/72062794-c359fa00-32d8-11ea-8e2d-e6e71cc2b9a8.jpg)
