### ISSUE TITLE
Cada grupo activo debe documentar quién tiene llaves

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/asrob-uc3m.github.io#32]
https://github.com/asrob-uc3m/estatutos/issues/18 resultó en https://github.com/asrob-uc3m/estatutos/blob/master/llaves.md ([perma](https://github.com/asrob-uc3m/estatutos/blob/4fc20c22f2da512036d724a37c2b3327f09fd759/llaves.md)), cito:
> Llave de la puerta de la nave
Cada grupo de trabajo activo puede tener hasta 2 copias de la misma. La página de cada grupo dentro de la web se actualiza para documentar quién tiene llave(s) en cada momento.
Llave del armario 1
Cada grupo de trabajo activo puede tener hasta 2 copias de la misma. La página de cada grupo dentro de la web se actualiza para documentar quién tiene llave(s) en cada momento.

Por tanto, falta por que cada grupo de la [web actual](https://github.com/asrob-uc3m/asrob-uc3m.github.io/tree/c715eea2330be95934e17ae8d38d52b41998602f) documente quién tiene llaves:
- [x] Printer One: A Clone Wars Story
- [x] Robot Devastation
- [x] F.E.N.I.X.
- [x] RoboFactory

**Comment by GioSunrider** [comment]
He añadido el commit 18a4bae8ee6167681e996bf3888a5fe289a351d8 para el Grupo de Printer One.

**Comment by jgvictores** [comment]
> He añadido el commit 18a4bae para el Grupo de Printer One.

Gracias por la info!
Respecto a cómo funciona la web... ¿estamos seguros que esa info puesta así se renderiza sin modificar nada de la infrestructura?

**Comment by GioSunrider** [comment]
He estado comprobando la web y no ha cambiado la infraestructura, lo unico que acabo de darme cuenta que la informacion no es mostrada.

**Comment by jgvictores** [comment]
Sí, me refería a que había que modificar la infraestructura para que se renderizara. :smile:
- Infraestructura actualizada en 6f49122 y e8e8769
- Etiqueta actualizada para Printer One en b57c016
- Info añadida para Robot Devastation en 9ab3c51

**Comment by GioSunrider** [comment]
Ah vale vale, eso no sabía hacerlo, pero genial!! Muchas gracias por el cambio @jgvictores

**Comment by JorFru** [comment]
https://github.com/asrob-uc3m/asrob-uc3m.github.io/commit/ed8362753844e0e69f6096c346a039b4ef565915
Etiqueta puesta para FENIX. (pero actualmente no ha recibido la llave todavía)

**Comment by jgvictores** [comment]
ping @asrob-uc3m/robofactory 

PS: Tal vez related https://github.com/asrob-uc3m/actas/issues/171

**Comment by David-Estevez** [comment]
Robofactory actualizado. Yo sólo tengo llave del armario via ASROB (lo dejo escrito aquí para que haya constancia de ello).

Lista de acciones por hacer:

* [x] Documentar el parámetro "keys_info" en las instrucciones de configuración de la página que hay en el README.md
* [ ] Proporcionar llaves a aquellas personas que todavía no dispongan de ellas.

**Comment by jgvictores** [comment]
> Documentar el parámetro "keys_info" en las instrucciones de configuración de la página que hay en el README.md

Hecho en bc204d0. Aproveché para hacer lo mismo para "url_playlist" vía f1e586e.

> Proporcionar llaves a aquellas personas que todavía no dispongan de ellas.

El fin de "Cada grupo activo debe documentar quién tiene llaves" es "Cada grupo activo debe documentar quién tiene llaves". Por partes:
- `Yo sólo tengo llave del armario via ASROB` de https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/32#issuecomment-442031927 -> Documentado vía fe3f682.
- `pero actualmente no ha recibido la llave todavía` de https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/32#issuecomment-438403808 -> Abierto https://github.com/asrob-uc3m/actas/issues/182 y documentado vía 46f5494.

Para mayor trazabilidad en [actas](https://github.com/asrob-uc3m/actas), he creado la etiqueta [llaves](https://github.com/asrob-uc3m/actas/issues?q=is%3Aissue+is%3Aopen+label%3Allaves) y animo a que se utilice ahí en caso de detectar alguna anomalía con respecto al [apartado correspondiente de los estatutos](https://github.com/asrob-uc3m/estatutos/blob/master/llaves.md) ([permalink](https://github.com/asrob-uc3m/estatutos/blob/4fc20c22f2da512036d724a37c2b3327f09fd759/llaves.md)). Con esto considero que el estado actual de llaves de grupos activos está documentado en asrob-uc3m.github.io y procedo a cerrar la issue.

**Comment by GioSunrider** [comment]
No sé ya dónde colocar esto, pero creo que igual este es el mejor sitio.
Pensando en el tema de las llaves, ¿No sería conveniente mostrar en la web a todos los miembros del grupo con llaves?
Me refiero a, independiente de los estatutos que ya están claros, ese apartado no es más que informativo y dado que muchos estamos en diferentes grupos igual deberían aparecer los nombres de los miembros. Todo esto viene a que es la principal fuente de información para los miembros en caso de duda de quien les puede abrir.
No sé si me he explicado bien o no ni si veis por dónde van mis tiros.

**Comment by jgvictores** [comment]
P.ej. 18a4bae8ee6167681e996bf3888a5fe289a351d8 se renderizó en https://asrob.uc3m.es/workgroups/2017-05-28-printer-one.html

¿Algo más que hacer aquí?

**Comment by jgvictores** [comment]
Edit: se había arreglado en b57c016c66a58a096a1cc48a2a1aa5e73ca230c1 para que figurase en https://asrob.uc3m.es/workgroups/2017-05-28-printer-one.html

**Comment by GioSunrider** [comment]
Si, algo asi, que todos los miembros con llaves del grupo figuren, de cara a informacion al resto.

**Comment by jgvictores** [comment]
Comentado con @GioSunrider la idea es ampliar la info de los grupos para contemplar todas las llaves que se posean aunque sea por vías no contempladas por los estatutos (e.g. llave nave a través de Departamento). Cierro issue, dejando abiertas 2 alternativas:
1. Editar directamente (se puede apuntar a esta issue en commit)
2. En caso de duda (cómo editar, o duda si alguien de un determinado grupo debería figurar) abrir nueva issue especificando el caso concreto.

**Comment by jgvictores** [comment]
PD: Como precedente de esta práctica: https://github.com/asrob-uc3m/asrob-uc3m.github.io/commit/fe3f6824b4877b067c9268815b4729599d4db9bc donde se aprovecha que es un espacio de texto libre para especificar que una de las llaves no viene vía Estatutos de ASROB.
